### ISSUE TITLE
PDF signature verification library?

### ISSUE THREAD

**Issue by keerati** [ETDA/etax-xades#16]
Hi. 

This is not an issue on this library itself but more like a question about signature verification in general. Please feel free to close this issue at any time.

I wonder if there is a Java library for PDF signature verification that works the same way to this website https://validation.teda.th/webportal/#/validate because I only see this repository, which is for XML if I understand correctly.

Or is there a documentation describing how to do the verification that meets ETDA standard?

Thank you in advance.

**Comment by nathamETDA** [comment]
@keerati 
Yes, this repository is for XAdES signature (XML) verification which is a part of verification process of "validation.teda.th".

For Java library, there are iText (it might require license if you use it comercially) and PDFBox. However they do only some verification parts not as the same way as "validation.teda.th" because the website added some certificate verification.

I'm sorry that there is not any document describe verification standard yet.

If you have any further questions about verification, you can send them to eservice@etda.or.th.
