### ISSUE TITLE
Can't use signed-ETDA-invoice.xml to Verify in e-tax web

### ISSUE THREAD

**Issue by phutisukt** [ETDA/etax-xades#3]
in https://etax.rd.go.th/etax_staticpage/app/#/index/support/validateschema#top ,I can't verify with signed-ETDA-invoice.xml  in resource directory

**Comment by pragasitcha** [comment]
@phutisukt  
May you please provide us a file or capture of an error ?.

**Comment by phutisukt** [comment]
@pragasitcha 
When I check in E-Tax Website (I used signed-ETDA-invoice.xml from folder resource in this Project) 
![image](https://user-images.githubusercontent.com/36686893/47145238-6fd64780-d2f3-11e8-8d00-80b54101f1b3.png)

![image](https://user-images.githubusercontent.com/36686893/47145215-65b44900-d2f3-11e8-90d3-221e21ad2e81.png)

When I Check in Xades Verify (C#) result is Signature is invalid.

P.S. but when is user verify-ETDA-invoice get result Error code=ECER : 010 and can check in Xades Verify(return True)

**Comment by pragasitcha** [comment]
@phutisukt phutisukt signed-ETDA-invoice.xml and verify-ETDA-invoice.xml on master branch is exactly same file. When we send theses two file to validate on RD's website it will return result like this which is correct.

![image](https://user-images.githubusercontent.com/26761030/47146410-29361c80-d2f6-11e8-87d3-cefcb25dd579.png)

First row is schema,schematron the result is Pass.

Second row will gave you an "ECER : 010 ไม่ผ่านการตรวจสอบ เนื่องจากใบรับรองอิเล็กทรอนิกส์นี้ไม่ถูกรับรองโดยกรมสรรพากร".ECER 10 says that PKCS12 file (.P12) you use to sign this XML  is not in trusted root of RD's website.This validation shall not passed until you have bought certificate from right Provider(TDID).
As if you use our .P12 that provided in this project it definitely gave you "ECER 10" because we created this key ourselves for testing purpose.

From an error ESNT009 picture says the XML file you put on website is already edited after signing. This editing also covered a space. Just only added accidentally space on the file,will makes you get ESTN009.
I suggested that you could check these two files's MD5 using following command. The MD5 should be the same value.

![image](https://user-images.githubusercontent.com/26761030/47147195-e9703480-d2f7-11e8-9e9d-0fff1901d871.png)

**Comment by phutisukt** [comment]
Ok,Thank you
